/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import java.awt.Color;
import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Toolkit;
import javax.swing.JLabel;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 *
 * @author New_Pc
 */
public class vista6 extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public vista6() {
    	setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\New_Pc\\Pictures\\asercor.png"));
    	setTitle("ASERCOR SAS");
    	setResizable(false);
    	getContentPane().setBackground(new Color(204, 255, 204));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel1.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 16));
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 16));
        txtUsuario = new javax.swing.JTextField();
        txtUsuario.setFont(new Font("Microsoft JhengHei UI", Font.PLAIN, 15));
        btnEntrar = new javax.swing.JButton();
        btnEntrar.addKeyListener(new KeyAdapter() {
        	@Override
        	public void keyPressed(KeyEvent e) {
        	}
        });
        btnEntrar.setForeground(new Color(0, 100, 0));
        btnEntrar.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 15));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        
        JLabel lblNewLabel_6 = new JLabel("MaycolCG © ");
        lblNewLabel_6.setForeground(new Color(0, 128, 0));
        lblNewLabel_6.setFont(new Font("Book Antiqua", Font.BOLD | Font.ITALIC, 8));
        
        JLabel lblNewLabel = new JLabel("Ingreso a Sistema");
        lblNewLabel.setForeground(new Color(0, 100, 0));
        lblNewLabel.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 30));
        
        txtPassword = new JPasswordField();
        txtPassword.setFont(new Font("Microsoft JhengHei UI", Font.PLAIN, 15));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(351, Short.MAX_VALUE)
        			.addComponent(lblNewLabel_6, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        		.addGroup(layout.createSequentialGroup()
        			.addGap(150)
        			.addComponent(btnEntrar)
        			.addContainerGap(182, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(68)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(lblNewLabel)
        				.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        					.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        						.addComponent(jLabel2)
        						.addPreferredGap(ComponentPlacement.UNRELATED)
        						.addComponent(txtPassword))
        					.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        						.addComponent(jLabel1)
        						.addPreferredGap(ComponentPlacement.UNRELATED)
        						.addComponent(txtUsuario, 158, 158, 158))))
        			.addGap(83))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(36)
        			.addComponent(lblNewLabel)
        			.addPreferredGap(ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(txtUsuario, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(28)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(txtPassword)
        				.addComponent(jLabel2))
        			.addGap(44)
        			.addComponent(btnEntrar)
        			.addGap(43)
        			.addComponent(lblNewLabel_6, GroupLayout.PREFERRED_SIZE, 11, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtUsuario;
    private JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnEntrar() {
        return btnEntrar;
    }

    public void setBtnEntrar(JButton btnEntrar) {
        this.btnEntrar = btnEntrar;
    }

    public JTextField getTxtUsuario() {
        return txtUsuario;
    }

    public void setTxtUsuario(JTextField txtUsuario) {
        this.txtUsuario = txtUsuario;
    }

	public JPasswordField getTxtPassword() {
		return txtPassword;
	}

	public void setTxtPassword(JPasswordField txtPassword) {
		this.txtPassword = txtPassword;
	}

    
}
