/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JList;
import javax.swing.JTable;
import java.awt.Toolkit;
import javax.swing.JTextPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JComboBox;
import javax.swing.DefaultComboBoxModel;
import java.awt.SystemColor;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.event.AncestorListener;
import javax.swing.event.AncestorEvent;
import java.awt.event.ContainerAdapter;
import java.awt.event.ContainerEvent;
import javax.swing.ListSelectionModel;
import java.awt.List;
import javax.swing.AbstractListModel;
import javax.swing.UIManager;
import javax.swing.border.LineBorder;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JTextArea;
import javax.swing.JProgressBar;
import java.awt.Scrollbar;
import java.awt.TextArea;
import java.awt.ScrollPane;
import javax.swing.ScrollPaneConstants;

/**
 *
 * @author New_Pc
 */
public class vista3 extends javax.swing.JFrame {

	/**
	 * Creates new form vista3
	 */



	public vista3() {
		getContentPane().setEnabled(false);
		getContentPane().setBackground(new Color(204, 255, 204));
		setBackground(new Color(51, 0, 102));
		getContentPane().setForeground(SystemColor.textHighlight);
		getContentPane().setFont(new Font("Microsoft YaHei UI", Font.BOLD, 10));
		setAutoRequestFocus(false);
		setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\New_Pc\\Pictures\\asercor.png"));
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel1.setForeground(new Color(0, 102, 0));
		jLabel2 = new javax.swing.JLabel();
		jLabel2.setForeground(new Color(0, 100, 0));
		jLabel3 = new javax.swing.JLabel();
		jLabel3.setForeground(new Color(0, 100, 0));
		jLabel4 = new javax.swing.JLabel();
		jLabel4.setForeground(new Color(0, 100, 0));
		jLabel5 = new javax.swing.JLabel();
		jLabel5.setForeground(new Color(0, 100, 0));
		jLabel6 = new javax.swing.JLabel();
		jLabel6.setForeground(new Color(0, 100, 0));
		btn_buscar = new javax.swing.JButton();
		btn_buscar.addKeyListener(new KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent e) {
			}
		});
		btn_buscar.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			}
		});
		btn_buscar.setForeground(new Color(51, 0, 102));
		btn_cancelar = new javax.swing.JButton();
		btn_cancelar.addKeyListener(new KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent e) {
			}
		});
		btn_cancelar.setForeground(new Color(51, 0, 102));
		btn_guardar = new javax.swing.JButton();
		btn_guardar.addKeyListener(new KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent e) {
			}
		});
		btn_guardar.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			}
		});
		btn_guardar.setForeground(new Color(51, 0, 102));
		jLabel7 = new javax.swing.JLabel();
		jLabel7.setForeground(new Color(0, 100, 0));
		txt_cedula = new javax.swing.JTextField();
		txt_cedula.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 14));
		txt_cedula.setForeground(new Color(25, 25, 112));
		txt_nombre = new javax.swing.JTextField();
		txt_nombre.setEditable(false);
		txt_nombre.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 14));
		txt_nombre.setForeground(new Color(25, 25, 112));
		txt_telefono1 = new javax.swing.JTextField();
		txt_telefono1.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 14));
		txt_telefono1.setForeground(new Color(25, 25, 112));
		txt_telefono1.setEditable(false);
		txt_correo = new javax.swing.JTextField();
		txt_correo.setEditable(false);
		txt_correo.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 14));
		txt_correo.setForeground(new Color(25, 25, 112));
		txt_direccion = new javax.swing.JTextField();
		txt_direccion.setEditable(false);
		txt_direccion.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 14));
		txt_direccion.setForeground(new Color(25, 25, 112));
		txt_ciudad = new javax.swing.JTextField();
		txt_ciudad.setEditable(false);
		txt_ciudad.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 14));
		txt_ciudad.setForeground(new Color(25, 25, 112));
		jLabel9 = new javax.swing.JLabel();
		jLabel9.setForeground(new Color(0, 100, 0));
		txt_telefono2 = new javax.swing.JTextField();
		txt_telefono2.setForeground(new Color(25, 25, 112));
		txt_telefono2.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 14));
		txt_telefono2.setEditable(false);
		txt_telefono3 = new javax.swing.JTextField();
		txt_telefono3.setEditable(false);
		txt_telefono3.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 14));
		txt_telefono3.setForeground(new Color(25, 25, 112));
		jLabel10 = new javax.swing.JLabel();
		jLabel10.setForeground(new Color(0, 100, 0));
		txt_telefono4 = new javax.swing.JTextField();
		txt_telefono4.setEditable(false);
		txt_telefono4.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 14));
		txt_telefono4.setForeground(new Color(25, 25, 112));
		jLabel11 = new javax.swing.JLabel();
		jLabel11.setForeground(new Color(0, 100, 0));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("ASERCOR SAS ");

		jLabel1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
		jLabel1.setText("Informacion Cliente");

		jLabel2.setFont(new Font("Microsoft JhengHei", Font.BOLD, 16)); // NOI18N
		jLabel2.setText("Cedula:");

		jLabel3.setFont(new Font("Microsoft JhengHei", Font.BOLD, 16)); // NOI18N
		jLabel3.setText("Nombre:");

		jLabel4.setFont(new Font("Microsoft JhengHei", Font.BOLD, 16)); // NOI18N
		jLabel4.setText("Telefono1:");

		jLabel5.setFont(new Font("Microsoft JhengHei", Font.BOLD, 16)); // NOI18N
		jLabel5.setText("Correo:");

		jLabel6.setFont(new Font("Microsoft JhengHei", Font.BOLD, 16)); // NOI18N
		jLabel6.setText("Direccion:");

		btn_buscar.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 16)); // NOI18N
		btn_buscar.setText("Buscar");

		btn_cancelar.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 16)); // NOI18N
		btn_cancelar.setText("Salir");

		btn_guardar.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 18)); // NOI18N
		btn_guardar.setText("Guardar Gestion");

		jLabel7.setFont(new Font("Microsoft JhengHei", Font.BOLD, 16)); // NOI18N
		jLabel7.setText("Ciudad:");

		jLabel9.setFont(new Font("Microsoft JhengHei", Font.BOLD, 16)); // NOI18N
		jLabel9.setText("Telefono2:");

		jLabel10.setFont(new Font("Microsoft JhengHei", Font.BOLD, 16)); // NOI18N
		jLabel10.setText("Telefono3:");

		jLabel11.setFont(new Font("Microsoft JhengHei", Font.BOLD, 16)); // NOI18N
		jLabel11.setText("Telefono4:");

		JLabel lblDepartamento = new JLabel();
		lblDepartamento.setForeground(new Color(0, 100, 0));
		lblDepartamento.setText("Departamento:");
		lblDepartamento.setFont(new Font("Microsoft JhengHei", Font.BOLD, 16));

		txt_dpto = new JTextField();
		txt_dpto.setEditable(false);
		txt_dpto.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 14));
		txt_dpto.setForeground(new Color(25, 25, 112));

		JLabel lblNewLabel = new JLabel("Asesor:");
		lblNewLabel.setForeground(new Color(0, 100, 0));
		lblNewLabel.setFont(new Font("Microsoft YaHei UI", Font.PLAIN, 16));

		txt_asesor = new JTextField();
		txt_asesor.setForeground(new Color(25, 25, 112));
		txt_asesor.setEditable(false);
		txt_asesor.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 14));
		txt_asesor.setColumns(10);

		JLabel lblFecha = new JLabel("Fecha:");
		lblFecha.setForeground(new Color(0, 100, 0));
		lblFecha.setFont(new Font("Microsoft YaHei UI", Font.PLAIN, 16));

		JLabel lblHora = new JLabel("Hora:");
		lblHora.setForeground(new Color(51, 0, 102));
		lblHora.setFont(new Font("Microsoft YaHei UI", Font.PLAIN, 16));

		JLabel lblCampaa = new JLabel("Proyecto:");
		lblCampaa.setForeground(new Color(0, 100, 0));
		lblCampaa.setFont(new Font("Microsoft YaHei UI", Font.PLAIN, 16));

		txt_campaña = new JTextField();
		txt_campaña.setForeground(new Color(25, 25, 112));
		txt_campaña.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 14));
		txt_campaña.setEditable(false);
		txt_campaña.setColumns(10);

		scrollPane = new JScrollPane();
		scrollPane.setViewportBorder(new LineBorder(new Color(0, 100, 0), 0, true));
		scrollPane.addAncestorListener(new AncestorListener() {
			public void ancestorAdded(AncestorEvent event) {
			}

			public void ancestorMoved(AncestorEvent event) {
			}

			public void ancestorRemoved(AncestorEvent event) {
			}

		});
		scrollPane.setToolTipText("scroll");

		lblInformacinDeObligaci = new JLabel();
		lblInformacinDeObligaci.setForeground(new Color(0, 102, 0));
		lblInformacinDeObligaci.setText("Informacion de Obligacion");
		lblInformacinDeObligaci.setFont(new Font("Candara", Font.BOLD, 22));

		lblHistoricoGestin = new JLabel();
		lblHistoricoGestin.setForeground(new Color(0, 102, 0));
		lblHistoricoGestin.setText("Gestion Historica");
		lblHistoricoGestin.setFont(new Font("Candara", Font.BOLD, 22));

		scrollPane_1 = new JScrollPane();
		scrollPane_1.setViewportBorder(new LineBorder(new Color(0, 100, 0), 0, true));

		lblInformacinDeGestin = new JLabel();
		lblInformacinDeGestin.setForeground(new Color(0, 102, 0));
		lblInformacinDeGestin.setText("Informacion de Gestión");
		lblInformacinDeGestin.setFont(new Font("Candara", Font.BOLD, 24));

		lblNuevaGestin = new JLabel();
		lblNuevaGestin.setForeground(new Color(0, 102, 0));
		lblNuevaGestin.setText("Nueva Gestión");
		lblNuevaGestin.setFont(new Font("Candara", Font.BOLD, 24));

		txt_obligacionGestion = new JTextField();
		txt_obligacionGestion.setFont(new Font("Microsoft JhengHei UI", Font.PLAIN, 15));
		txt_obligacionGestion.setForeground(new Color(51, 0, 102));
		txt_obligacionGestion.setColumns(10);

		jLabel11_1 = new JLabel();
		jLabel11_1.setForeground(new Color(0, 100, 0));
		jLabel11_1.setToolTipText("");
		jLabel11_1.setText("Obligacion:");
		jLabel11_1.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 15));

		lblNewLabel_1 = new JLabel("Tel_Contacto:");
		lblNewLabel_1.setForeground(new Color(0, 100, 0));
		lblNewLabel_1.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 15));

		txt_telefonoGestion = new JTextField();
		txt_telefonoGestion.setFont(new Font("Microsoft JhengHei UI", Font.PLAIN, 15));
		txt_telefonoGestion.setForeground(new Color(51, 0, 102));
		txt_telefonoGestion.setColumns(10);

		lblNewLabel_2 = new JLabel("Tipificacion:");
		lblNewLabel_2.setForeground(new Color(0, 100, 0));
		lblNewLabel_2.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 15));

		lblNewLabel_3 = new JLabel("Fecha de Pago:");
		lblNewLabel_3.setForeground(new Color(0, 100, 0));
		lblNewLabel_3.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 15));

		lblNewLabel_4 = new JLabel("Vlr de Pago:");
		lblNewLabel_4.setForeground(new Color(0, 100, 0));
		lblNewLabel_4.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 15));

		txt_FechaPago = new JTextField();
		txt_FechaPago.setFont(new Font("Microsoft JhengHei UI", Font.PLAIN, 15));
		txt_FechaPago.setForeground(new Color(51, 0, 102));
		txt_FechaPago.setColumns(10);

		txt_VlrPago = new JTextField();
		txt_VlrPago.setFont(new Font("Microsoft JhengHei UI", Font.PLAIN, 15));
		txt_VlrPago.setForeground(new Color(51, 0, 102));
		txt_VlrPago.setColumns(10);

		lblNewLabel_5 = new JLabel("Observacion:");
		lblNewLabel_5.setForeground(new Color(0, 100, 0));
		lblNewLabel_5.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 15));

		btn_guardar.setForeground(new Color(51, 0, 102));
		btn_guardar.setText("Guardar Gestion");
		btn_guardar.setFont(new Font("Microsoft JhengHei UI", Font.PLAIN, 18));

		lblNewLabel_6 = new JLabel("MaycolCG © ");
		lblNewLabel_6.setForeground(new Color(0, 128, 0));
		lblNewLabel_6.setFont(new Font("Book Antiqua", Font.BOLD | Font.ITALIC, 8));

		txt_FechaGestion = new JTextField();
		txt_FechaGestion.setForeground(new Color(25, 25, 112));
		txt_FechaGestion.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 14));
		txt_FechaGestion.setEditable(false);
		txt_FechaGestion.setColumns(10);

		txt_HoraGestion = new JTextField();
		txt_HoraGestion.setForeground(new Color(25, 25, 112));
		txt_HoraGestion.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 14));
		txt_HoraGestion.setEditable(false);
		txt_HoraGestion.setColumns(10);
		
		JComboBox Box_Tipificacion = new JComboBox();
		Box_Tipificacion.setBackground(new Color(255, 255, 255));
		Box_Tipificacion.setFont(new Font("Microsoft JhengHei UI", Font.PLAIN, 15));
		Box_Tipificacion.setModel(new DefaultComboBoxModel(new String[] {"----------Seleccione----------", "Promesa de Pago", "Dificultad de Acuerdo", "Promesa Incumplido", "Pago Confirmado", "Al Día", "Retiro de Gestión", "Mensaje con Tercero", "Mensaje", "No Contesta", "Ocupado", "No Contacto", "Ilocalizado", "Renuente", "Fallecido"}));
		
		btnModificar = new JButton("Modificar Registro");
		btnModificar.addKeyListener(new KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent e) {
			}
		});
		btnModificar.setForeground(new Color(25, 25, 112));
		btnModificar.setFont(new Font("Microsoft JhengHei UI", Font.BOLD, 15));
		
		JScrollPane scrollPane_2 = new JScrollPane();
		scrollPane_2.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
									.addGap(27)
									.addGroup(layout.createParallelGroup(Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
											.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE)
											.addGap(18)
											.addComponent(txt_cedula, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE)
											.addGap(26)
											.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE)
											.addPreferredGap(ComponentPlacement.UNRELATED)
											.addComponent(txt_nombre, GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE))
										.addGroup(layout.createSequentialGroup()
											.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
											.addPreferredGap(ComponentPlacement.RELATED)
											.addComponent(txt_correo, GroupLayout.PREFERRED_SIZE, 277, GroupLayout.PREFERRED_SIZE)
											.addPreferredGap(ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
											.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 78, GroupLayout.PREFERRED_SIZE)
											.addGap(18)
											.addComponent(txt_direccion, GroupLayout.PREFERRED_SIZE, 341, GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
											.addComponent(jLabel4)
											.addPreferredGap(ComponentPlacement.RELATED)
											.addComponent(txt_telefono1, GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
											.addPreferredGap(ComponentPlacement.RELATED)
											.addComponent(jLabel9)
											.addPreferredGap(ComponentPlacement.UNRELATED)
											.addComponent(txt_telefono2, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE)
											.addPreferredGap(ComponentPlacement.UNRELATED)
											.addComponent(jLabel10)
											.addPreferredGap(ComponentPlacement.RELATED)
											.addComponent(txt_telefono3, GroupLayout.PREFERRED_SIZE, 114, GroupLayout.PREFERRED_SIZE)
											.addPreferredGap(ComponentPlacement.UNRELATED)
											.addComponent(jLabel11)
											.addPreferredGap(ComponentPlacement.RELATED)
											.addComponent(txt_telefono4, GroupLayout.PREFERRED_SIZE, 105, GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
											.addPreferredGap(ComponentPlacement.RELATED)
											.addGroup(layout.createParallelGroup(Alignment.TRAILING)
												.addComponent(scrollPane_1, GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
												.addGroup(layout.createSequentialGroup()
													.addGroup(layout.createParallelGroup(Alignment.TRAILING)
														.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 840, GroupLayout.PREFERRED_SIZE)
														.addGroup(layout.createSequentialGroup()
															.addComponent(jLabel7)
															.addPreferredGap(ComponentPlacement.UNRELATED)
															.addGroup(layout.createParallelGroup(Alignment.TRAILING)
																.addComponent(lblInformacinDeObligaci)
																.addGroup(layout.createSequentialGroup()
																	.addComponent(txt_ciudad, GroupLayout.PREFERRED_SIZE, 261, GroupLayout.PREFERRED_SIZE)
																	.addGap(33)
																	.addComponent(lblDepartamento, GroupLayout.PREFERRED_SIZE, 128, GroupLayout.PREFERRED_SIZE)))
															.addPreferredGap(ComponentPlacement.RELATED)
															.addComponent(txt_dpto, GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)))
													.addPreferredGap(ComponentPlacement.RELATED)))))
									.addGap(78))
								.addGroup(layout.createSequentialGroup()
									.addGap(285)
									.addComponent(lblHistoricoGestin)
									.addPreferredGap(ComponentPlacement.RELATED)))
							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup()
									.addGroup(layout.createParallelGroup(Alignment.LEADING)
										.addComponent(lblNewLabel)
										.addComponent(lblFecha)
										.addComponent(lblCampaa)
										.addGroup(layout.createSequentialGroup()
											.addPreferredGap(ComponentPlacement.RELATED)
											.addGroup(layout.createParallelGroup(Alignment.TRAILING)
												.addComponent(lblNewLabel_3)
												.addComponent(lblNewLabel_4))))
									.addGap(6))
								.addGroup(layout.createSequentialGroup()
									.addComponent(lblNewLabel_2)
									.addGap(10))
								.addGroup(layout.createSequentialGroup()
									.addGroup(layout.createParallelGroup(Alignment.TRAILING)
										.addComponent(jLabel11_1)
										.addComponent(lblNewLabel_1))
									.addGap(6))
								.addGroup(layout.createSequentialGroup()
									.addComponent(lblNewLabel_5)
									.addGap(10))))
						.addGroup(layout.createSequentialGroup()
							.addGap(364)
							.addComponent(jLabel1)
							.addPreferredGap(ComponentPlacement.RELATED)))
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addComponent(txt_FechaPago, GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
								.addGroup(layout.createSequentialGroup()
									.addGap(18)
									.addGroup(layout.createParallelGroup(Alignment.TRAILING)
										.addComponent(txt_campaña, GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
										.addGroup(layout.createSequentialGroup()
											.addComponent(txt_FechaGestion, GroupLayout.PREFERRED_SIZE, 135, GroupLayout.PREFERRED_SIZE)
											.addPreferredGap(ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
											.addComponent(lblHora)
											.addPreferredGap(ComponentPlacement.RELATED)
											.addComponent(txt_HoraGestion, GroupLayout.PREFERRED_SIZE, 128, GroupLayout.PREFERRED_SIZE))
										.addComponent(txt_asesor, GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)))
								.addGroup(layout.createSequentialGroup()
									.addPreferredGap(ComponentPlacement.RELATED)
									.addGroup(layout.createParallelGroup(Alignment.LEADING)
										.addComponent(lblInformacinDeGestin)
										.addComponent(txt_telefonoGestion, GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
										.addComponent(txt_obligacionGestion, GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)))
								.addComponent(Box_Tipificacion, 0, 406, Short.MAX_VALUE)
								.addGroup(layout.createSequentialGroup()
									.addPreferredGap(ComponentPlacement.UNRELATED)
									.addGroup(layout.createParallelGroup(Alignment.LEADING)
										.addComponent(scrollPane_2, GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
										.addComponent(txt_VlrPago, GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE))))
							.addGap(66))
						.addGroup(layout.createSequentialGroup()
							.addGap(126)
							.addComponent(lblNuevaGestin, GroupLayout.PREFERRED_SIZE, 162, GroupLayout.PREFERRED_SIZE)
							.addContainerGap())))
				.addGroup(layout.createSequentialGroup()
					.addGap(138)
					.addComponent(btnModificar)
					.addGap(64)
					.addComponent(btn_buscar)
					.addGap(54)
					.addComponent(btn_cancelar)
					.addPreferredGap(ComponentPlacement.RELATED, 601, Short.MAX_VALUE)
					.addComponent(btn_guardar)
					.addGap(189))
				.addGroup(layout.createSequentialGroup()
					.addContainerGap(1480, Short.MAX_VALUE)
					.addComponent(lblNewLabel_6)
					.addContainerGap())
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(lblInformacinDeGestin)
						.addComponent(jLabel1))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel2)
								.addComponent(txt_cedula, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
								.addComponent(txt_nombre, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3))
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel4)
								.addComponent(jLabel11)
								.addComponent(txt_telefono4, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
								.addComponent(txt_telefono3, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
								.addComponent(txt_telefono1, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel10)
								.addComponent(txt_telefono2, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel9))
							.addGap(2)
							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup()
									.addGroup(layout.createParallelGroup(Alignment.LEADING)
										.addComponent(jLabel5)
										.addGroup(layout.createParallelGroup(Alignment.BASELINE)
											.addComponent(txt_direccion, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
											.addComponent(jLabel6)))
									.addGap(12))
								.addGroup(layout.createSequentialGroup()
									.addComponent(txt_correo, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
									.addPreferredGap(ComponentPlacement.RELATED)))
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addComponent(txt_dpto, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(txt_ciudad, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
									.addComponent(jLabel7)
									.addComponent(lblDepartamento, GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))))
						.addGroup(layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(lblNewLabel)
								.addComponent(txt_asesor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
									.addGap(23)
									.addGroup(layout.createParallelGroup(Alignment.TRAILING)
										.addComponent(lblFecha)
										.addComponent(lblHora)))
								.addGroup(layout.createSequentialGroup()
									.addGap(18)
									.addComponent(txt_FechaGestion, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup()
									.addGap(18)
									.addComponent(txt_HoraGestion, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)))
							.addGap(18)
							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(txt_campaña, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
								.addComponent(lblCampaa))))
					.addGap(33)
					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(lblInformacinDeObligaci, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
						.addGroup(layout.createSequentialGroup()
							.addComponent(lblNuevaGestin, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)))
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addGap(3)
							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(txt_obligacionGestion, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel11_1))
							.addGap(10)
							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(txt_telefonoGestion, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
								.addComponent(lblNewLabel_1))
							.addGap(27)
							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(lblNewLabel_2, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
								.addComponent(Box_Tipificacion, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(txt_FechaPago, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
								.addComponent(lblNewLabel_3))
							.addGap(18)
							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(lblNewLabel_4)
								.addComponent(txt_VlrPago, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE))
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
									.addGap(81)
									.addComponent(lblNewLabel_5, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup()
									.addGap(18)
									.addComponent(scrollPane_2, GroupLayout.PREFERRED_SIZE, 138, GroupLayout.PREFERRED_SIZE))))
						.addGroup(layout.createSequentialGroup()
							.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 135, GroupLayout.PREFERRED_SIZE)
							.addGap(75)
							.addComponent(lblHistoricoGestin)
							.addGap(4)
							.addComponent(scrollPane_1, GroupLayout.PREFERRED_SIZE, 136, GroupLayout.PREFERRED_SIZE)))
					.addGap(39)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(btn_guardar, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
						.addComponent(btn_buscar)
						.addComponent(btn_cancelar)
						.addComponent(btnModificar, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))
					.addGap(45)
					.addComponent(lblNewLabel_6)
					.addContainerGap())
		);
		
		textArea = new JTextArea();
		textArea.setFont(new Font("Microsoft JhengHei UI", Font.PLAIN, 16));
		textArea.setLineWrap(true);
		textArea.setWrapStyleWord(true);
		scrollPane_2.setViewportView(textArea);
		
		table_GestionHistorica = new JTable();
		table_GestionHistorica.setForeground(new Color(25, 25, 112));
		table_GestionHistorica.setBorder(new LineBorder(new Color(0, 100, 0), 1, true));
		table_GestionHistorica.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		table_GestionHistorica.setSurrendersFocusOnKeystroke(true);
		table_GestionHistorica.setCellSelectionEnabled(true);
		table_GestionHistorica.setFont(new Font("Microsoft JhengHei UI", Font.PLAIN, 12));
		table_GestionHistorica.setModel(new DefaultTableModel(
			new Object[][] {
				{null, null, null, null, null, null, null, null, null},
				{null, null, null, null, null, null, null, null, null},
				{null, null, null, null, null, null, null, null, null},
				{null, null, null, null, null, null, null, null, null},
				{null, null, null, null, null, null, null, null, null},
				{null, null, null, null, null, null, null, null, null},
				{null, null, null, null, null, null, null, null, null},
			},
			new String[] {
				"Fecha_Gestion", "Hora", "Obligacion", "Tipificacion", "Observacion", "Telefono Contacto", "Asesor", "Fecha_Pago", "Vlr_Pago "
			}
		) {
			Class[] columnTypes = new Class[] {
				Object.class, Object.class, Object.class, String.class, String.class, String.class, String.class, Object.class, Object.class
			};
			public Class getColumnClass(int columnIndex) {
				return columnTypes[columnIndex];
			}
			boolean[] columnEditables = new boolean[] {
				false, false, false, false, true, false, false, false, false
			};
			public boolean isCellEditable(int row, int column) {
				return columnEditables[column];
			}
		});
		table_GestionHistorica.getColumnModel().getColumn(0).setResizable(false);
		table_GestionHistorica.getColumnModel().getColumn(0).setPreferredWidth(49);
		table_GestionHistorica.getColumnModel().getColumn(0).setMinWidth(2);
		table_GestionHistorica.getColumnModel().getColumn(1).setResizable(false);
		table_GestionHistorica.getColumnModel().getColumn(1).setPreferredWidth(48);
		table_GestionHistorica.getColumnModel().getColumn(1).setMinWidth(2);
		table_GestionHistorica.getColumnModel().getColumn(2).setResizable(false);
		table_GestionHistorica.getColumnModel().getColumn(2).setMinWidth(2);
		table_GestionHistorica.getColumnModel().getColumn(3).setPreferredWidth(88);
		table_GestionHistorica.getColumnModel().getColumn(3).setMinWidth(2);
		table_GestionHistorica.getColumnModel().getColumn(4).setPreferredWidth(213);
		table_GestionHistorica.getColumnModel().getColumn(4).setMinWidth(7);
		table_GestionHistorica.getColumnModel().getColumn(5).setResizable(false);
		table_GestionHistorica.getColumnModel().getColumn(5).setPreferredWidth(93);
		table_GestionHistorica.getColumnModel().getColumn(6).setResizable(false);
		table_GestionHistorica.getColumnModel().getColumn(6).setMinWidth(2);
		table_GestionHistorica.getColumnModel().getColumn(7).setResizable(false);
		table_GestionHistorica.getColumnModel().getColumn(7).setPreferredWidth(70);
		table_GestionHistorica.getColumnModel().getColumn(8).setResizable(false);
		table_GestionHistorica.getColumnModel().getColumn(8).setPreferredWidth(57);
		scrollPane_1.setViewportView(table_GestionHistorica);

		jtable_InfoObligacion = new JTable();
		jtable_InfoObligacion.setBorder(new LineBorder(new Color(0, 100, 0), 1, true));
		jtable_InfoObligacion.addContainerListener(new ContainerAdapter() {
			@Override
			public void componentRemoved(ContainerEvent e) {

			}
		});
		jtable_InfoObligacion.setForeground(new Color(25, 25, 112));
		jtable_InfoObligacion.setCellSelectionEnabled(true);
		jtable_InfoObligacion.setFont(new Font("Microsoft JhengHei UI", Font.PLAIN, 15));
		scrollPane.setViewportView(jtable_InfoObligacion);
		jtable_InfoObligacion.setModel(new DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null }, { null, null, null, null, null, null },
						{ null, null, null, null, null, null }, { null, null, null, null, null, null },
						{ null, null, null, null, null, null }, { null, null, null, null, null, null },
						{ null, null, null, null, null, null }, },
				new String[] { "Obligacion", "Referencia", "Producto", "Dias_Mora", "Saldo_Gestionable",
						"Plan_Descuento" }) {
			
			Class[] columnTypes = new Class[] { Integer.class, Integer.class, String.class, Integer.class, Float.class,
					Float.class };

			public Class getColumnClass(int columnIndex) {
				return columnTypes[columnIndex];
			}
		});
		jtable_InfoObligacion.getColumnModel().getColumn(4).setPreferredWidth(100);
		jtable_InfoObligacion.getColumnModel().getColumn(5).setPreferredWidth(106);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btn_buscar;
	private javax.swing.JButton btn_cancelar;
	private javax.swing.JButton btn_guardar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JTextField txt_cedula;
	private javax.swing.JTextField txt_correo;
	private javax.swing.JTextField txt_nombre;
	private javax.swing.JTextField txt_ciudad;
	private javax.swing.JTextField txt_direccion;
	private javax.swing.JTextField txt_telefono1;
	private javax.swing.JTextField txt_telefono2;
	private javax.swing.JTextField txt_telefono3;
	private javax.swing.JTextField txt_telefono4;
	private JTextField txt_dpto;
	private JTextField txt_asesor;
	private JTextField txt_campaña;
	private JTable jtable_InfoObligacion;
	private JScrollPane scrollPane;
	private JLabel lblInformacinDeObligaci;
	private JLabel lblHistoricoGestin;
	private JScrollPane scrollPane_1;
	private JTable table_GestionHistorica;
	private JLabel lblInformacinDeGestin;
	private JLabel lblNuevaGestin;
	private JTextField txt_obligacionGestion;
	private JLabel jLabel11_1;
	private JLabel lblNewLabel_1;
	private JTextField txt_telefonoGestion;
	private JLabel lblNewLabel_2;
	private JLabel lblNewLabel_3;
	private JLabel lblNewLabel_4;
	private JTextField txt_FechaPago;
	private JTextField txt_VlrPago;
	private JLabel lblNewLabel_5;
	private JLabel lblNewLabel_6;
	private JTextField txt_FechaGestion;
	private JTextField txt_HoraGestion;
	private JButton btnModificar;
	private JTextArea textArea;

	// End of variables declaration//GEN-END:variables
	public javax.swing.JButton getBtn_buscar() {
		return btn_buscar;
	}


	public void setBtn_buscar(javax.swing.JButton btn_buscar) {
		this.btn_buscar = btn_buscar;
	}

	public javax.swing.JButton getBtn_cancelar() {
		return btn_cancelar;
	}

	public void setBtn_cancelar(javax.swing.JButton btn_cancelar) {
		this.btn_cancelar = btn_cancelar;
	}

	public javax.swing.JButton getBtn_guardar() {
		return btn_guardar;
	}

	public void setBtn_guardar(javax.swing.JButton btn_guardar) {
		this.btn_guardar = btn_guardar;
	}

	public javax.swing.JLabel getjLabel1() {
		return jLabel1;
	}

	public void setjLabel1(javax.swing.JLabel jLabel1) {
		this.jLabel1 = jLabel1;
	}

	public javax.swing.JLabel getjLabel10() {
		return jLabel10;
	}

	public void setjLabel10(javax.swing.JLabel jLabel10) {
		this.jLabel10 = jLabel10;
	}

	public javax.swing.JLabel getjLabel11() {
		return jLabel11;
	}

	public void setjLabel11(javax.swing.JLabel jLabel11) {
		this.jLabel11 = jLabel11;
	}

	public javax.swing.JLabel getjLabel2() {
		return jLabel2;
	}

	public void setjLabel2(javax.swing.JLabel jLabel2) {
		this.jLabel2 = jLabel2;
	}

	public javax.swing.JLabel getjLabel3() {
		return jLabel3;
	}

	public void setjLabel3(javax.swing.JLabel jLabel3) {
		this.jLabel3 = jLabel3;
	}

	public javax.swing.JLabel getjLabel4() {
		return jLabel4;
	}

	public void setjLabel4(javax.swing.JLabel jLabel4) {
		this.jLabel4 = jLabel4;
	}

	public javax.swing.JLabel getjLabel5() {
		return jLabel5;
	}

	public void setjLabel5(javax.swing.JLabel jLabel5) {
		this.jLabel5 = jLabel5;
	}

	public javax.swing.JLabel getjLabel6() {
		return jLabel6;
	}

	public void setjLabel6(javax.swing.JLabel jLabel6) {
		this.jLabel6 = jLabel6;
	}

	public javax.swing.JLabel getjLabel7() {
		return jLabel7;
	}

	public void setjLabel7(javax.swing.JLabel jLabel7) {
		this.jLabel7 = jLabel7;
	}

	public javax.swing.JLabel getjLabel9() {
		return jLabel9;
	}

	public void setjLabel9(javax.swing.JLabel jLabel9) {
		this.jLabel9 = jLabel9;
	}

	public javax.swing.JTextField getTxt_cedula() {
		return txt_cedula;
	}

	public void setTxt_cedula(javax.swing.JTextField txt_cedula) {
		this.txt_cedula = txt_cedula;
	}

	public javax.swing.JTextField getTxt_correo() {
		return txt_correo;
	}

	public void setTxt_correo(javax.swing.JTextField txt_correo) {
		this.txt_correo = txt_correo;
	}

	public javax.swing.JTextField getTxt_nombre() {
		return txt_nombre;
	}

	public void setTxt_nombre(javax.swing.JTextField txt_nombre) {
		this.txt_nombre = txt_nombre;
	}

	public javax.swing.JTextField getTxt_ciudad() {
		return txt_ciudad;
	}

	public void setTxt_ciudad(javax.swing.JTextField txt_ciudad) {
		this.txt_ciudad = txt_ciudad;
	}

	public javax.swing.JTextField getTxt_direccion() {
		return txt_direccion;
	}

	public void setTxt_direccion(javax.swing.JTextField txt_direccion) {
		this.txt_direccion = txt_direccion;
	}

	public javax.swing.JTextField getTxt_telefono1() {
		return txt_telefono1;
	}

	public void setTxt_telefono1(javax.swing.JTextField txt_telefono1) {
		this.txt_telefono1 = txt_telefono1;
	}

	public javax.swing.JTextField getTxt_telefono2() {
		return txt_telefono2;
	}

	public void setTxt_telefono2(javax.swing.JTextField txt_telefono2) {
		this.txt_telefono2 = txt_telefono2;
	}

	public javax.swing.JTextField getTxt_telefono3() {
		return txt_telefono3;
	}

	public void setTxt_telefono3(javax.swing.JTextField txt_telefono3) {
		this.txt_telefono3 = txt_telefono3;
	}

	public javax.swing.JTextField getTxt_telefono4() {
		return txt_telefono4;
	}

	public void setTxt_telefono4(javax.swing.JTextField txt_telefono4) {
		this.txt_telefono4 = txt_telefono4;
	}

	public JTextField getTxt_dpto() {
		return txt_dpto;
	}

	public void setTxt_dpto(JTextField txt_dpto) {
		this.txt_dpto = txt_dpto;
	}

	public JTextField getTxt_asesor() {
		return txt_asesor;
	}

	public void setTxt_asesor(JTextField txt_asesor) {
		this.txt_asesor = txt_asesor;
	}

	public JTextField getTxt_FechaGestion() {
		return txt_FechaGestion;
	}

	public void setTxt_FechaGestion(JTextField txt_FechaGestion) {
		this.txt_FechaGestion = txt_FechaGestion;
	}

	public JTextField getTxt_HoraGestion() {
		return txt_HoraGestion;
	}

	public void setTxt_HoraGestion(JTextField txt_HoraGestion) {
		this.txt_HoraGestion = txt_HoraGestion;
	}

	public JTextField getTxt_campaña() {
		return txt_campaña;
	}

	public void setTxt_campaña(JTextField txt_campaña) {
		this.txt_campaña = txt_campaña;
	}

	public JTable getJtable_InfoObligacion() {
		return jtable_InfoObligacion;
	}

	public void setJtable_InfoObligacion(JTable jtable_InfoObligacion) {
		this.jtable_InfoObligacion = jtable_InfoObligacion;
	}

	public JScrollPane getScrollPane() {
		return scrollPane;
	}

	public void setScrollPane(JScrollPane scrollPane) {
		this.scrollPane = scrollPane;
	}

	public JLabel getLblInformacinDeObligaci() {
		return lblInformacinDeObligaci;
	}

	public void setLblInformacinDeObligaci(JLabel lblInformacinDeObligaci) {
		this.lblInformacinDeObligaci = lblInformacinDeObligaci;
	}

	public JLabel getLblHistoricoGestin() {
		return lblHistoricoGestin;
	}

	public void setLblHistoricoGestin(JLabel lblHistoricoGestin) {
		this.lblHistoricoGestin = lblHistoricoGestin;
	}

	public JScrollPane getScrollPane_1() {
		return scrollPane_1;
	}

	public void setScrollPane_1(JScrollPane scrollPane_1) {
		this.scrollPane_1 = scrollPane_1;
	}

	public JTable getTable_GestionHistorica() {
		return table_GestionHistorica;
	}

	public void setTable_GestionHistorica(JTable table_GestionHistorica) {
		this.table_GestionHistorica = table_GestionHistorica;
	}

	public JLabel getLblInformacinDeGestin() {
		return lblInformacinDeGestin;
	}

	public void setLblInformacinDeGestin(JLabel lblInformacinDeGestin) {
		this.lblInformacinDeGestin = lblInformacinDeGestin;
	}

	public JLabel getLblNuevaGestin() {
		return lblNuevaGestin;
	}

	public void setLblNuevaGestin(JLabel lblNuevaGestin) {
		this.lblNuevaGestin = lblNuevaGestin;
	}

	public JTextField getTxt_obligacionGestion() {
		return txt_obligacionGestion;
	}

	public void setTxt_obligacionGestion(JTextField txt_obligacionGestion) {
		this.txt_obligacionGestion = txt_obligacionGestion;
	}

	public JLabel getjLabel11_1() {
		return jLabel11_1;
	}

	public void setjLabel11_1(JLabel jLabel11_1) {
		this.jLabel11_1 = jLabel11_1;
	}

	public JLabel getLblNewLabel_1() {
		return lblNewLabel_1;
	}

	public void setLblNewLabel_1(JLabel lblNewLabel_1) {
		this.lblNewLabel_1 = lblNewLabel_1;
	}

	public JTextField getTxt_telefonoGestion() {
		return txt_telefonoGestion;
	}

	public void setTxt_telefonoGestion(JTextField txt_telefonoGestion) {
		this.txt_telefonoGestion = txt_telefonoGestion;
	}

	public JLabel getLblNewLabel_2() {
		return lblNewLabel_2;
	}

	public void setLblNewLabel_2(JLabel lblNewLabel_2) {
		this.lblNewLabel_2 = lblNewLabel_2;
	}

	public JLabel getLblNewLabel_3() {
		return lblNewLabel_3;
	}

	public void setLblNewLabel_3(JLabel lblNewLabel_3) {
		this.lblNewLabel_3 = lblNewLabel_3;
	}

	public JLabel getLblNewLabel_4() {
		return lblNewLabel_4;
	}

	public void setLblNewLabel_4(JLabel lblNewLabel_4) {
		this.lblNewLabel_4 = lblNewLabel_4;
	}

	public JTextField getTxt_FechaPago() {
		return txt_FechaPago;
	}

	public void setTxt_FechaPago(JTextField txt_FechaPago) {
		this.txt_FechaPago = txt_FechaPago;
	}

	public JTextField getTxt_VlrPago() {
		return txt_VlrPago;
	}

	public void setTxt_VlrPago(JTextField txt_VlrPago) {
		this.txt_VlrPago = txt_VlrPago;
	}

	public JLabel getLblNewLabel_5() {
		return lblNewLabel_5;
	}

	public void setLblNewLabel_5(JLabel lblNewLabel_5) {
		this.lblNewLabel_5 = lblNewLabel_5;
	}

	public JLabel getLblNewLabel_6() {
		return lblNewLabel_6;
	}
	public void setLblNewLabel_6(JLabel lblNewLabel_6) {
		this.lblNewLabel_6 = lblNewLabel_6;
	}

	public JButton getBtnModificar() {
		return btnModificar;
	}

	public void setBtnModificar(JButton btnModificar) {
		this.btnModificar = btnModificar;
	}

	public JTextArea getTextArea() {
		return textArea;
	}

	public void setTextArea(JTextArea textArea) {
		this.textArea = textArea;
	}
	
}